prompts:
  - "Standard_v3"

defaultTest:
  assert:
    - type: python
      value: file://assertions.py

providers:
  - id: "python:provider.py"
    config:
      provider: "Ollama"
      local: true
      model: "qwen2"
      language: "zh_traditional"
      corrector_mode: "standard"

tests:
  - datasets/smoke_test.csv
