"""Change cost from float to Numeric(15, 12)

Revision ID: dad5039f4770
Revises: 
Create Date: 2025-04-02 08:21:25.112931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dad5039f4770'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'interaction',
        'cost',
        existing_type=sa.Float(),  # 或 sa.DOUBlE(precision=53)，視原始欄位定義
        type_=sa.Numeric(15, 12),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'interaction',
        'cost',
        existing_type=sa.Numeric(15, 12),
        type_=sa.Float(),
        existing_nullable=False
    )
    # ### end Alembic commands ###
